import { forwardRef, type ReactNode, useMemo } from "react";
import { formatUsdc, type MarketplaceDeliverable } from "../api.ts";
import { strategyLabel } from "./utils.ts";
import { auditPaperTitle, isAuditDeliverable } from "./audit.ts";
import { billPaperTitle, isBillDeliverable } from "./bill.ts";
import { resolveDeliverablePayload } from "./payload.ts";
import { isIntelPayload, intelDeliverableKicker } from "./defi-agents.tsx";

export const PaperDocument = forwardRef<
  HTMLElement,
  { job: MarketplaceDeliverable; children: ReactNode; payload?: Record<string, unknown> | null }
>(function PaperDocument({ job, children, payload: payloadProp }, ref) {
  const date = new Date(job.at * 1000).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const strategy = strategyLabel(job.plan?.strategy);
  const isAudit = isAuditDeliverable(job);
  const isBill = !isAudit && isBillDeliverable(job);
  const payload = useMemo(() => payloadProp ?? resolveDeliverablePayload(job), [job, payloadProp]);
  const isIntel = payload != null && isIntelPayload(payload);
  const title = isAudit
    ? auditPaperTitle(job, payload)
    : isBill
      ? billPaperTitle(job, payload)
      : isIntel && (typeof payload?.token === "string" || typeof payload?.tokenSymbol === "string")
        ? `${String(payload.token ?? payload.tokenSymbol)} — Token Research`
        : isIntel && typeof payload?.address === "string"
          ? `Wallet ${String(payload.address).slice(0, 10)}…`
          : (job.brief ?? "Deliverable Report");
  const showAbstract =
    !isAudit && !isBill && !isIntel && job.plan?.reason && !/^single-agent task\.?$/i.test(job.plan.reason);
  const sheetClass = isAudit
    ? " library-paper-sheet--audit"
    : isBill
      ? " library-paper-sheet--bill"
      : isIntel
        ? " library-paper-sheet--intel"
        : "";
  const kicker = isAudit
    ? "Butler Security Audit"
    : isBill
      ? "Butler Utility Quote"
      : isIntel
        ? intelDeliverableKicker(payload)
        : "Butler Research Deliverable";

  return (
    <article className={`library-paper-sheet${sheetClass}`} ref={ref}>
      <header className="paper-masthead">
        <p className="paper-kicker">
          {kicker}
        </p>
        <h1 className="paper-title">{title}</h1>
        <div className="paper-byline">
          <span>{strategy}</span>
          <span className="paper-byline-sep" aria-hidden>
            ·
          </span>
          <time dateTime={new Date(job.at * 1000).toISOString()}>{date}</time>
          <span className="paper-byline-sep" aria-hidden>
            ·
          </span>
          <span>${formatUsdc(job.totalUsdc)} USDC</span>
        </div>
        {showAbstract && (
          <div className="paper-abstract">
            <p className="paper-abstract-label">Abstract</p>
            <p className="paper-abstract-text">{job.plan!.reason}</p>
          </div>
        )}
      </header>

      <div className="paper-content">{children}</div>

      <footer className="paper-colophon">
        <p>Generated by Butler Agentic hub · Arc testnet · {date}</p>
      </footer>
    </article>
  );
});

/** Serializes the paper article DOM for print/PDF export. */
export function serializePaperForExport(root: HTMLElement): string {
  const clone = root.cloneNode(true) as HTMLElement;
  clone.querySelectorAll("[data-export-hide]").forEach((el) => el.remove());
  return clone.innerHTML;
}
