import { forwardRef, type ReactNode } from "react";
import { formatUsdc, type MarketplaceDeliverable } from "../api.ts";
import { strategyLabel } from "./utils.ts";

export const PaperDocument = forwardRef<
  HTMLElement,
  { job: MarketplaceDeliverable; children: ReactNode }
>(function PaperDocument({ job, children }, ref) {
  const date = new Date(job.at * 1000).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const strategy = strategyLabel(job.plan?.strategy);

  return (
    <article className="library-paper-sheet" ref={ref}>
      <header className="paper-masthead">
        <p className="paper-kicker">Butler Research Deliverable</p>
        <h1 className="paper-title">{job.brief ?? "Deliverable Report"}</h1>
        <div className="paper-byline">
          <span>{strategy}</span>
          <span className="paper-byline-sep" aria-hidden>
            ·
          </span>
          <time dateTime={new Date(job.at * 1000).toISOString()}>{date}</time>
          <span className="paper-byline-sep" aria-hidden>
            ·
          </span>
          <span>${formatUsdc(job.totalUsdc)} USDC</span>
        </div>
        {job.plan?.reason && (
          <div className="paper-abstract">
            <p className="paper-abstract-label">Abstract</p>
            <p className="paper-abstract-text">{job.plan.reason}</p>
          </div>
        )}
      </header>

      <div className="paper-content">{children}</div>

      <footer className="paper-colophon">
        <p>Generated by Butler Agent Marketplace · Arc testnet · {date}</p>
      </footer>
    </article>
  );
});

/** Serializes the paper article DOM for print/PDF export. */
export function serializePaperForExport(root: HTMLElement): string {
  const clone = root.cloneNode(true) as HTMLElement;
  clone.querySelectorAll("[data-export-hide]").forEach((el) => el.remove());
  return clone.innerHTML;
}
